server:
  port: 10201

spring:
  application:
    name: physical-book-meta
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0 #采样比例
  datasource:
    #初始化数据结构/数据
    schema: classpath:h2/schema.sql
    data: classpath:h2/test-data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

feign.hystrix.enabled: true

#这样才能访问 /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

logging:
  level:
    com.ynding.cloud.book: debug
    org.hibernate.SQL: WARN
    org.springframework.web: WARN