server:
  port: 10201

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:10101}/eureka/

spring:
  application:
    name: physical-book-meta
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0 #采样比例
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/yahaweilian/cloud-config.git
          searchPaths: /
  datasource:
    #初始化数据结构/数据
    schema: classpath:h2/schema.sql
    data: classpath:h2/test-data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

#这样才能访问 /actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

