version: '3'
services:

  seata-server:
    image: seataio/seata-server:latest
    hostname: seata-server
    ports:
      - 8091:8091
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=db
      - SEATA_CONFIG_NAME=/seata-server/resources/registry.conf
    volumes:
      - ./seata/registry.conf:/seata-server/resources/registry.conf
     ## - ./seata/file.conf:/seata-server/resources/file.conf
      - ../data/seata_server/logs:/root/logs/seata
    expose:
      - 8091
    networks:
      - sc-net