server:
  port: ${EUREKA_PORT:10101}

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    registerWithEureka: false #不注册自己
    fetchRegistry: false #不要在本地缓存注册表信息
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:10101}/eureka/

spring:
  application:
    name: core-server-eureka #指定服务名
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  zipkin:
#    base-url: localhost:9411 #docker不需要配置
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0 #采样比例
